In [1]:
import dash
from dash import dcc, html, Input, Output
import plotly.graph_objects as go
import numpy as np
import nibabel as nib
from scipy.ndimage import binary_dilation, generate_binary_structure
from sklearn.decomposition import PCA
from scipy.spatial.distance import cdist
import plotly.colors as pc
import matplotlib.pyplot as plt

from scipy.spatial import ConvexHull  # pip install -U concave_hull

from concave_hull import (  # noqa: F401
    concave_hull,
    concave_hull_indexes,
    convex_hull_indexes,
)

ModuleNotFoundError: No module named 'dash'

In [ ]:
# Load the NIfTI file
nii_file = nib.load(r"C:\Users\20202047\OneDrive - TU Eindhoven\Master\Year 1\Team Challenge\Data\corrected_masks\corrected_masks/corrected_mask_C0003.nii")
seg_data = nii_file.get_fdata()

def construct_matrix(file_path):
    # Load the NIfTI file
    img = nib.load(file_path)
    data = img.get_fdata()  # Convert to NumPy array

    # Print shape info
    print(f"Matrix shape: {data.shape}")

    # Create and return a copy of the data (ensuring it's a NumPy array)
    return np.array(data, dtype=np.uint8)  # Convert to uint8 if intensities are discrete (0,1,2)


In [ ]:
matrix_corr_mask = seg_data
print(f"Unique values in the corrected mask matrix: ",np.unique(matrix_corr_mask))

# Keep only the '2' values
matrix_aneurysm = np.zeros_like(matrix_corr_mask)
matrix_aneurysm[matrix_corr_mask == 2] = 2
print(f"Unique values in the aneurysm matrix: ",np.unique(matrix_aneurysm))

matrix_vessels = np.zeros_like(matrix_corr_mask)
matrix_vessels[matrix_corr_mask == 1] = 1
print(f"Unique values in the surface boundary green matrix: ",np.unique(matrix_vessels))

# Define 26-connectivity structure in 3D (one pixel away in any direction)
structure = generate_binary_structure(3, 3)  # 3D, full 26-neighborhood

# Find coordinates for aneurysm points (value = 2)
x, y, z = np.where(matrix_corr_mask == 2)

# Find coordinates for correlation mask points (value = 1)
x1, y1, z1 = np.where(matrix_corr_mask == 1)

# Create a mask of neighboring points that touch value = 1
dilated_mask = binary_dilation(matrix_corr_mask == 1, structure=structure)
print("Unique values in dilated_mask:", np.unique(dilated_mask))

# Find aneurysm points (value = 2) that have at least one 1-neighbor
green_mask = (matrix_corr_mask == 2) & dilated_mask
x_green, y_green, z_green = np.where(green_mask)

#Create matrix with surface points on the aneurysm-vessel boundary
surface_matrix = np.zeros_like(matrix_aneurysm)
surface_matrix = green_mask

# Get surface points
surface_points = np.argwhere(surface_matrix == 1)
print(surface_points)

# Compute PCA
pca = PCA(n_components=3)
pca.fit(surface_points)

# The normal is the eigenvector corresponding to the smallest eigenvalue
normal_vector = pca.components_[-1]  # Smallest component gives normal

# Ensure it's a unit vector
normal_vector /= np.linalg.norm(normal_vector)
print('Normal vector Ina: ',normal_vector)

# Choose a point to originate the normal (e.g., mean of surface)
origin = np.mean(surface_points, axis=0)
print('Origin Ina: ',origin)

# Step 1: Compute local coordinate system
normal_vector /= np.linalg.norm(normal_vector)  # Normalize normal  #TODO: no need again?

# Pick a reference vector for basis computation   #TODO: no need?
if abs(normal_vector[0]) < 0.9:
    reference_vector = np.array([1, 0, 0])
else:
    reference_vector = np.array([0, 1, 0])

# Compute basis vectors
basis_vector_1 = np.cross(normal_vector, reference_vector)
basis_vector_1 /= np.linalg.norm(basis_vector_1)

basis_vector_2 = np.cross(normal_vector, basis_vector_1)
basis_vector_2 /= np.linalg.norm(basis_vector_2)

# Construct the transformation matrix (Global -> Local)
T = np.column_stack([basis_vector_1, basis_vector_2, normal_vector]).T  # Transpose to map to local
print(T)
print()

# Step 2: Transform all surface points into the local coordinate system
origin = np.mean(surface_points, axis=0)
centered_points = surface_points - origin
local_points = (T @ centered_points.T).T  # Transform each point to local [x', y', n']
print(local_points)

# Extract x' and y' coordinates for the scatter plot
x_prime = local_points[:, 0]  # x' coordinates
y_prime = local_points[:, 1]  # y' coordinates

projected_2d = local_points[:, :2]  # Extract x and y coordinates

# Your 2D points (make sure 'projected_2d' is already defined) #TODO: fix comment
points = np.array(projected_2d)

# Add the first point to the end of the array to close the loop
points = np.vstack([points, points[0]])

# Compute Convex Hull using scipy
convex_hull = ConvexHull(points[:, :2])  # points are already 2D (N-by-2)

# Compute the Concave Hull and plot it
idxes = concave_hull_indexes(
    points[:, :2],
    length_threshold=0,
    # convex_hull_indexes=convex_hull.vertices.astype(np.int32),
)
print(idxes)

# Fill the area inside the Concave Hull with black color
concave_x = points[idxes, 0]  # X coordinates of the concave hull points
concave_y = points[idxes, 1]  # Y coordinates of the concave hull points

# Get the concave hull points
concave_hull_points = points[idxes]
print(concave_hull_points)

# Function to project points onto a 1D line at a given angle
def project_onto_line(points, angle):
    # Convert angle to radians
    angle_rad = np.radians(angle)

    # Define the unit vector for the projection direction
    direction = np.array([np.cos(angle_rad), np.sin(angle_rad)])

    # Project each point of the concave hull onto the direction (dot product)
    projection = np.dot(points, direction)

    return projection

# Define angles to project the concave hull onto (0 to 180 degrees)
angles = np.linspace(0, 360, 361)  # From 0 to 180 degrees
print(angles)
projections = []
projection_ranges = []

# Plot projections for each angle and find the angle with the shortest projection range
for angle in angles:
    # Project the concave hull onto the 1D line at each angle
    projection = project_onto_line(concave_hull_points, angle)

    # Calculate the range of the projection (max - min)
    projection_range = np.max(projection) - np.min(projection)
    projection_ranges.append(projection_range)

# print(projection_ranges)
angles_ranges = [(angles[i], projection_ranges[i]) for i in range (0, 360)]
angles_ranges_sorted = sorted(angles_ranges, key=lambda x: x[1])
print('-----')
print(angles_ranges_sorted)

# Find the angle with the shortest 1D projection
shortest_projection_angle = angles[np.argmin(projection_ranges)]
#print(shortest_projection_angle)

# Find the angle with the longest 1D projection
longest_projection_angle = angles[np.argmax(projection_ranges)]
#print(longest_projection_angle)

# Step 1: Calculate the unit vector in the 2D plane corresponding to the projection angle
shortest_projection_angle_rad = np.deg2rad(angles_ranges_sorted[0][0])  # Convert theta to radians
u_2d_local = np.array([np.cos(shortest_projection_angle_rad), np.sin(shortest_projection_angle_rad)])

# Transformation matrix (local to global)
T_inv = np.linalg.inv(T)

# Step 2: Transform the 2D local vector back to the global coordinate system
u_2d_global = T_inv @ np.append(u_2d_local, 0)  # Append 0 for the normal component (since u_2d_local is 2D)

# make a list with 3D projection vectors sorted from most optimal projection vector to least optimal

shortest_projection_angle_rad_list = np.deg2rad(angles_ranges_sorted)

u_2d_local_list = []
for angle in shortest_projection_angle_rad_list:
    u_2d_local_list.append(np.array([np.cos(angle[0]), np.sin(angle[0])]))
#print(u_2d_local_list)

u_2d_global_list = []
for u_2d_local in u_2d_local_list:
    u_2d_global_list.append(T_inv @ np.append(u_2d_local, 0))
#print(u_2d_global_list)

# Compute the list with global projection directions
projection_direction_list = []
for u_2d_global in u_2d_global_list:
    projection_direction_list.append(np.cross(normal_vector, u_2d_global))
    projection_direction_list[-1] /= np.linalg.norm(projection_direction_list[-1])  # Normalize

#print(projection_direction_list)


Unique values in the corrected mask matrix:  [0. 1. 2.]
Unique values in the aneurysm matrix:  [0. 2.]
Unique values in the surface boundary green matrix:  [0. 1.]
Unique values in dilated_mask: [False  True]
[[124 102 155]
 [124 102 156]
 [124 102 157]
 [124 103 156]
 [124 103 157]
 [125 101 153]
 [125 101 154]
 [125 101 155]
 [125 102 153]
 [125 102 154]
 [125 102 155]
 [125 102 156]
 [125 103 154]
 [125 103 155]
 [125 103 156]
 [125 103 157]
 [125 103 158]
 [125 104 156]
 [125 104 157]
 [125 104 158]
 [125 105 159]
 [126 101 152]
 [126 101 153]
 [126 102 151]
 [126 102 152]
 [126 102 153]
 [126 102 154]
 [126 103 151]
 [126 103 152]
 [126 103 153]
 [126 103 154]
 [126 103 155]
 [126 103 156]
 [126 104 154]
 [126 104 155]
 [126 104 156]
 [126 104 157]
 [126 104 158]
 [126 104 159]
 [126 105 156]
 [126 105 157]
 [126 105 158]
 [126 105 159]
 [126 106 157]
 [126 106 158]
 [126 106 159]
 [126 107 159]
 [126 108 159]
 [127 102 151]
 [127 103 150]
 [127 103 151]
 [127 103 152]
 [127 103 1

In [2]:
# Set a condition on biggest tolerable variance from smallest neck width
# Example: 7% bigger neck width than the smallest neck width
# The condition will depend on whether we want to prioritise smallest neck width or smallest overlap

def count_valid_pairs(pairs, neck_width_tolerance=0.07):
    """
    Counts the number of (angle, length) pairs where the length is within
    neck_width_tolerance of the smallest length in the sorted list.

    :param pairs: List of (angle, length) tuples sorted by length.
    :param neck_width_tolerance: Tolerance factor (default is 0.07 or 7%).
    :return: Number of pairs satisfying the condition.
    """
    if not pairs:
        return 0

    min_length = pairs[0][1]  # The first entry has the smallest length
    threshold = min_length * (1 + neck_width_tolerance)

    count = sum(1 for _, length in pairs if length <= threshold)
    return count

how_many_planes = count_valid_pairs(angles_ranges_sorted)
print(how_many_planes)

NameError: name 'angles_ranges_sorted' is not defined

In [ ]:
# Downsampling function
def downsample_coordinates(x, y, z, factor=2):
    indices = np.arange(0, len(x), factor)
    return x[indices], y[indices], z[indices]

# Find vessel and aneurysm coordinates
x1, y1, z1 = downsample_coordinates(*np.where(seg_data == 1), factor=2)
x2, y2, z2 = downsample_coordinates(*np.where(seg_data == 2), factor=2)

print(normal_vector)
center_x,center_y,center_z = origin[0], origin[1], origin[2]
print(center_x,center_y,center_z)

# Compute two perpendicular vectors
v1, v2 = basis_vector_1, basis_vector_2
print(v1,v2)

# Find valid plane length
def find_plane_endpoints(center, direction, image_shape):
    return min(min(abs((0 - center[i]) / direction[i]), abs((image_shape[i] - center[i]) / direction[i])) if direction[i] != 0 else float('inf') for i in range(3))

# Compute maximum width
def calculate_max_width(x, y, z):
    points = np.vstack((x, y, z)).T  # Combine x, y, z coordinates into a single array of points
    distances = cdist(points, points)  # Calculate pairwise distances between all points
    np.fill_diagonal(distances, 0)  # Set the diagonal to zero because we don't want to compare a point to itself
    max_dist = np.max(distances)  # Find the maximum distance
    return max_dist

image_shape = seg_data.shape  # Image dimensions

# Generate points on the plane
def generate_plane_points(left_start, left_end, right_start, right_end, num_points=100):
    # Create a grid of points on the plane using the two directions
    vector1 = left_end - left_start
    vector2 = right_start - left_start
    points = []
    for i in np.linspace(0, 1, num_points):
        for j in np.linspace(0, 1, num_points):
            point = left_start + i * vector1 + j * vector2
            points.append(point)
    return np.array(points)


# Count red pixels (vessel or aneurysm points)
def count_red_pixels_on_plane(points, seg_data):
    count = 0
    for point in points:
        # Round the point to nearest voxel indices (ensure they are within bounds)
        x, y, z = np.round(point).astype(int)
        if 0 <= x < seg_data.shape[0] and 0 <= y < seg_data.shape[1] and 0 <= z < seg_data.shape[2]:
            if seg_data[x, y, z] == 1:  # Assuming '1' corresponds to the red pixels (vessel)
                count += 1
    return count


[-0.28151866  0.76709104 -0.5764708 ]
128.50574712643677 104.45402298850574 154.69540229885058
[ 0.         -0.60076843 -0.7994231 ] [-0.95955575 -0.22505252  0.16912753]


In [ ]:
#make dictionary with angle and red pixel count
dict_angle = {}

for i, (angle, max_width) in enumerate(angles_ranges_sorted[0:how_many_planes]):

    print(angle, max_width)
    angle = angle

    angle_rad = np.deg2rad(angle)
    rotated_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
    # direction_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
    max_length = find_plane_endpoints([center_x, center_y, center_z], rotated_vector, image_shape)
    half_width = max_width / 2

    start = np.array([center_x, center_y, center_z])
    # left_start = start - half_width * v1 - half_width * v2
    # right_start = start + half_width * v1 + half_width * v2
    # left_end = left_start + direction_vector * max_length
    # right_end = right_start + direction_vector * max_length

    left_start = start + np.cos(angle_rad) * v1 * -half_width + np.sin(angle_rad) * v2 * -half_width
    right_start = start + np.cos(angle_rad) * v1 * half_width + np.sin(angle_rad) * v2 * half_width

    # Compute the direction vectors from 'start' to each point
    left_vector = left_start - start
    right_vector = right_start - start

    # Normalize the vectors to ensure correct scaling
    left_vector /= np.linalg.norm(left_vector)
    right_vector /= np.linalg.norm(right_vector)

    # Adjust left and right start to be exactly max_width apart
    left_start = start + left_vector * (-max_width / 2)
    right_start = start + right_vector * (max_width / 2)

    # Compute the perpendicular direction (cross product with normal_vector)
    perpendicular_direction = np.cross(normal_vector, left_vector)
    perpendicular_direction /= np.linalg.norm(perpendicular_direction)  # Normalize

    # Move the start points along the perpendicular direction
    left_start += perpendicular_direction * half_width
    right_start -= perpendicular_direction * half_width

    left_end = left_start + rotated_vector * max_length
    right_end = right_start + rotated_vector * max_length

    # Count red pixels on the plane
    red_pixel_count = count_red_pixels_on_plane(generate_plane_points(left_start, left_end, right_start, right_end, num_points=100), seg_data)
    print(f"Red pixel count on plane {angle  :.1f}° : {red_pixel_count}")
    #add red pixel count to dictionary
    dict_angle[angle] = red_pixel_count


64.0 9.823020670755295
Red pixel count on plane 64.0° : 100
244.0 9.823020670755295
Red pixel count on plane 244.0° : 69
63.0 9.842805908576565
Red pixel count on plane 63.0° : 96
243.0 9.842805908576565
Red pixel count on plane 243.0° : 67
65.0 9.842895116502444
Red pixel count on plane 65.0° : 104
245.0 9.842895116502445
Red pixel count on plane 245.0° : 74
62.0 9.859592932368685
Red pixel count on plane 62.0° : 95
242.0 9.859592932368685
Red pixel count on plane 242.0° : 63
66.0 9.859830154252315
Red pixel count on plane 66.0° : 105
246.0 9.859830154252316
Red pixel count on plane 246.0° : 77


In [ ]:
print(dict_angle)
# sorted_dict = sorted(dict_angle.items(), key=lambda x: x[1])
# print(sorted_dict)

{64.0: 100, 244.0: 69, 63.0: 96, 243.0: 67, 65.0: 104, 245.0: 74, 62.0: 95, 242.0: 63, 66.0: 105, 246.0: 77}


In [ ]:
dict_both_sides = {}
processed = set()

for angle, red_pixels in dict_angle.items():
    opposite_angle = angle + 180 if angle + 180 in dict_angle else angle - 180

    if opposite_angle in dict_angle and angle not in processed and opposite_angle not in processed:
        total_red_pixels = red_pixels + dict_angle[opposite_angle]
        chosen_angle = min((angle, red_pixels), (opposite_angle, dict_angle[opposite_angle]), key=lambda x: x[1])[0]
        paired_angle = max((angle, red_pixels), (opposite_angle, dict_angle[opposite_angle]), key=lambda x: x[1])[0]

        dict_both_sides[chosen_angle] = {paired_angle: total_red_pixels}
        processed.add(angle)
        processed.add(opposite_angle)

print(dict_both_sides)

# Sort dictionary based on the summed red pixel values
sorted_dict_both_sides = dict(sorted(dict_both_sides.items(), key=lambda item: list(item[1].values())[0]))

print(sorted_dict_both_sides)

{244.0: {64.0: 169}, 243.0: {63.0: 163}, 245.0: {65.0: 178}, 242.0: {62.0: 158}, 246.0: {66.0: 182}}
{242.0: {62.0: 158}, 243.0: {63.0: 163}, 244.0: {64.0: 169}, 245.0: {65.0: 178}, 246.0: {66.0: 182}}


#### Visualize the result

In [ ]:
# Dash app
app = dash.Dash(__name__)
app.layout = html.Div([
    html.H3("3D Visualization of Cerebral Vessels, Aneurysms, and Viewing Planes"),
    dcc.Graph(id='3d-plot', config={'scrollZoom': True}, style={'height': '80vh'}),
    html.Label("Number of Planes:"),
    dcc.Slider(id='num-planes-slider', min=1, max=360, step=1, value=how_many_planes,
               marks={i: str(i) for i in range(4, 37, 4)}, tooltip={"placement": "bottom", "always_visible": True})
])

# Generate a list of distinct colors from Plotly's predefined color scale
color_list = pc.qualitative.Set1  # or you can choose other color scales like Set2, Set3, etc.

@app.callback(Output('3d-plot', 'figure'), Input('num-planes-slider', 'value'))
def update_3d_plot(_):
    fig = go.Figure()

    # Add vessels, aneurysms, and connection region
    fig.add_trace(go.Scatter3d(x=x1, y=y1, z=z1, mode='markers', marker=dict(size=2, color='red'), name="Vessels"))
    fig.add_trace(go.Scatter3d(x=x2, y=y2, z=z2, mode='markers', marker=dict(size=2, color='blue'), name="Aneurysms"))
    fig.add_trace(go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=2, color='green'), name="Connection"))

    # Generate a list of distinct colors from Plotly's predefined color scale
    color_list = pc.qualitative.Set1  # Choose color set

    for i, (angle, max_width) in enumerate(angles_ranges_sorted[0:1]):
        plane_color = color_list[i % len(color_list)]  # Ensure we loop through the color list

        angle = angle

        angle_rad = np.deg2rad(angle)
        rotated_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
        # direction_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
        max_length = find_plane_endpoints([center_x, center_y, center_z], rotated_vector, image_shape)
        half_width = max_width / 2

        start = np.array([center_x, center_y, center_z])
        # left_start = start - half_width * v1 - half_width * v2
        # right_start = start + half_width * v1 + half_width * v2
        # left_end = left_start + direction_vector * max_length
        # right_end = right_start + direction_vector * max_length

        left_start = start + np.cos(angle_rad) * v1 * -half_width + np.sin(angle_rad) * v2 * -half_width
        right_start = start + np.cos(angle_rad) * v1 * half_width + np.sin(angle_rad) * v2 * half_width

        # Compute the direction vectors from 'start' to each point
        left_vector = left_start - start
        right_vector = right_start - start

        # Normalize the vectors to ensure correct scaling
        left_vector /= np.linalg.norm(left_vector)
        right_vector /= np.linalg.norm(right_vector)

        # Adjust left and right start to be exactly max_width apart
        left_start = start + left_vector * (-max_width / 2)
        right_start = start + right_vector * (max_width / 2)

        # Compute the perpendicular direction (cross product with normal_vector)
        perpendicular_direction = np.cross(normal_vector, left_vector)
        perpendicular_direction /= np.linalg.norm(perpendicular_direction)  # Normalize

        # Move the start points along the perpendicular direction
        left_start += perpendicular_direction * half_width
        right_start -= perpendicular_direction * half_width

        left_end = left_start + rotated_vector * max_length
        right_end = right_start + rotated_vector * max_length

        fig.add_trace(go.Mesh3d(
            x=[left_start[0], left_end[0], right_end[0], right_start[0]],
            y=[left_start[1], left_end[1], right_end[1], right_start[1]],
            z=[left_start[2], left_end[2], right_end[2], right_start[2]],
            i=[0, 1, 2, 0], j=[1, 2, 3, 2], k=[2, 3, 0, 3],
            opacity=0.5, color=plane_color, name=f"Plane {angle:.1f}°"
        ))

        # Count red pixels on the plane
        red_pixel_count = count_red_pixels_on_plane(generate_plane_points(left_start, left_end, right_start, right_end, num_points=100), seg_data)
        print(f"Color: {plane_color}, Angle: {angle:.1f}°, Width: {max_width}, Red pixel count on plane: {red_pixel_count}")

    fig.update_layout(scene=dict(xaxis_title="X", yaxis_title="Y", zaxis_title="Z"), margin=dict(l=0, r=0, b=0, t=0))
    return fig

if __name__ == '__main__':
    app.run_server(debug=True , port=8052)
    #app.run_server(debug=True)



Color: rgb(228,26,28), Angle: 64.0°, Width: 9.823020670755295, Red pixel count on plane: 100
Color: rgb(55,126,184), Angle: 244.0°, Width: 9.823020670755295, Red pixel count on plane: 69
Color: rgb(77,175,74), Angle: 63.0°, Width: 9.842805908576565, Red pixel count on plane: 96
Color: rgb(152,78,163), Angle: 243.0°, Width: 9.842805908576565, Red pixel count on plane: 67
Color: rgb(255,127,0), Angle: 65.0°, Width: 9.842895116502444, Red pixel count on plane: 104
Color: rgb(255,255,51), Angle: 245.0°, Width: 9.842895116502445, Red pixel count on plane: 74
Color: rgb(166,86,40), Angle: 62.0°, Width: 9.859592932368685, Red pixel count on plane: 95
Color: rgb(247,129,191), Angle: 242.0°, Width: 9.859592932368685, Red pixel count on plane: 63
Color: rgb(153,153,153), Angle: 66.0°, Width: 9.859830154252315, Red pixel count on plane: 105
Color: rgb(228,26,28), Angle: 246.0°, Width: 9.859830154252316, Red pixel count on plane: 77
