In [1]:
import dash
from dash import dcc, html, Input, Output
import plotly.graph_objects as go
import numpy as np
import nibabel as nib
from scipy.ndimage import binary_dilation, generate_binary_structure
from sklearn.decomposition import PCA
from scipy.spatial.distance import cdist
import plotly.colors as pc
import matplotlib.pyplot as plt

from scipy.spatial import ConvexHull  # pip install -U concave_hull

from concave_hull import (  # noqa: F401
    concave_hull,
    concave_hull_indexes,
    convex_hull_indexes,
)

In [2]:
# Load the NIfTI file
nii_file = nib.load(r"C:\Users\20202310\Desktop\Vakken jaar 1\Mix team challenge\Practical assignment\DATA\Team challenge 2024\Aneurysm_TC_data\C0002\corrected_mask_C0002.nii")
seg_data = nii_file.get_fdata()

def construct_matrix(file_path):
    # Load the NIfTI file
    img = nib.load(file_path)
    data = img.get_fdata()  # Convert to NumPy array

    # Print shape info
    print(f"Matrix shape: {data.shape}")

    # Create and return a copy of the data (ensuring it's a NumPy array)
    return np.array(data, dtype=np.uint8)  # Convert to uint8 if intensities are discrete (0,1,2)


In [3]:
matrix_corr_mask = seg_data
print(f"Unique values in the corrected mask matrix: ",np.unique(matrix_corr_mask))

# Keep only the '2' values
matrix_aneurysm = np.zeros_like(matrix_corr_mask)
matrix_aneurysm[matrix_corr_mask == 2] = 2
print(f"Unique values in the aneurysm matrix: ",np.unique(matrix_aneurysm))

matrix_vessels = np.zeros_like(matrix_corr_mask)
matrix_vessels[matrix_corr_mask == 1] = 1
print(f"Unique values in the surface boundary green matrix: ",np.unique(matrix_vessels))

# Define 26-connectivity structure in 3D (one pixel away in any direction)
structure = generate_binary_structure(3, 3)  # 3D, full 26-neighborhood

# Find coordinates for aneurysm points (value = 2)
x, y, z = np.where(matrix_corr_mask == 2)

# Find coordinates for correlation mask points (value = 1)
x1, y1, z1 = np.where(matrix_corr_mask == 1)

# Create a mask of neighboring points that touch value = 1
dilated_mask = binary_dilation(matrix_corr_mask == 1, structure=structure)
print("Unique values in dilated_mask:", np.unique(dilated_mask))

# Find aneurysm points (value = 2) that have at least one 1-neighbor
green_mask = (matrix_corr_mask == 2) & dilated_mask
x_green, y_green, z_green = np.where(green_mask)

#Create matrix with surface points on the aneurysm-vessel boundary
surface_matrix = np.zeros_like(matrix_aneurysm)
surface_matrix = green_mask

# Get surface points
surface_points = np.argwhere(surface_matrix == 1)
print(surface_points)

# Compute PCA
pca = PCA(n_components=3)
pca.fit(surface_points)

# The normal is the eigenvector corresponding to the smallest eigenvalue
normal_vector = pca.components_[-1]  # Smallest component gives normal

# Ensure it's a unit vector
normal_vector /= np.linalg.norm(normal_vector)
print('Normal vector Ina: ',normal_vector)

# Choose a point to originate the normal (e.g., mean of surface)
origin = np.mean(surface_points, axis=0)
print('Origin Ina: ',origin)

# Step 1: Compute local coordinate system
normal_vector /= np.linalg.norm(normal_vector)  # Normalize normal  #TODO: no need again?

# Pick a reference vector for basis computation   #TODO: no need?
if abs(normal_vector[0]) < 0.9:
    reference_vector = np.array([1, 0, 0])
else:
    reference_vector = np.array([0, 1, 0])

# Compute basis vectors
basis_vector_1 = np.cross(normal_vector, reference_vector)
basis_vector_1 /= np.linalg.norm(basis_vector_1)

basis_vector_2 = np.cross(normal_vector, basis_vector_1)
basis_vector_2 /= np.linalg.norm(basis_vector_2)

# Construct the transformation matrix (Global -> Local)
T = np.column_stack([basis_vector_1, basis_vector_2, normal_vector]).T  # Transpose to map to local
print(T)
print()

# Step 2: Transform all surface points into the local coordinate system
origin = np.mean(surface_points, axis=0)
centered_points = surface_points - origin
local_points = (T @ centered_points.T).T  # Transform each point to local [x', y', n']
print(local_points)

# Extract x' and y' coordinates for the scatter plot
x_prime = local_points[:, 0]  # x' coordinates
y_prime = local_points[:, 1]  # y' coordinates

projected_2d = local_points[:, :2]  # Extract x and y coordinates

# Your 2D points (make sure 'projected_2d' is already defined) #TODO: fix comment
points = np.array(projected_2d)

# Add the first point to the end of the array to close the loop
points = np.vstack([points, points[0]])

# Compute Convex Hull using scipy
convex_hull = ConvexHull(points[:, :2])  # points are already 2D (N-by-2)

# Compute the Concave Hull and plot it
idxes = concave_hull_indexes(
    points[:, :2],
    length_threshold=0,
    # convex_hull_indexes=convex_hull.vertices.astype(np.int32),
)
print(idxes)

# Fill the area inside the Concave Hull with black color
concave_x = points[idxes, 0]  # X coordinates of the concave hull points
concave_y = points[idxes, 1]  # Y coordinates of the concave hull points

# Get the concave hull points
concave_hull_points = points[idxes]
print(concave_hull_points)

# Function to project points onto a 1D line at a given angle
def project_onto_line(points, angle):
    # Convert angle to radians
    angle_rad = np.radians(angle)

    # Define the unit vector for the projection direction
    direction = np.array([np.cos(angle_rad), np.sin(angle_rad)])

    # Project each point of the concave hull onto the direction (dot product)
    projection = np.dot(points, direction)

    return projection

# Define angles to project the concave hull onto (0 to 180 degrees)
angles = np.linspace(0, 360, 361)  # From 0 to 180 degrees
print(angles)
projections = []
projection_ranges = []

# Plot projections for each angle and find the angle with the shortest projection range
for angle in angles:
    # Project the concave hull onto the 1D line at each angle
    projection = project_onto_line(concave_hull_points, angle)

    # Calculate the range of the projection (max - min)
    projection_range = np.max(projection) - np.min(projection)
    projection_ranges.append(projection_range)

# print(projection_ranges)
angles_ranges = [(angles[i], projection_ranges[i]) for i in range (0, 360)]
angles_ranges_sorted = sorted(angles_ranges, key=lambda x: x[1])
print('-----')
print(angles_ranges_sorted)

# Find the angle with the shortest 1D projection
shortest_projection_angle = angles[np.argmin(projection_ranges)]
#print(shortest_projection_angle)

# Find the angle with the longest 1D projection
longest_projection_angle = angles[np.argmax(projection_ranges)]
#print(longest_projection_angle)

# Step 1: Calculate the unit vector in the 2D plane corresponding to the projection angle
shortest_projection_angle_rad = np.deg2rad(angles_ranges_sorted[0][0])  # Convert theta to radians
u_2d_local = np.array([np.cos(shortest_projection_angle_rad), np.sin(shortest_projection_angle_rad)])

# Transformation matrix (local to global)
T_inv = np.linalg.inv(T)

# Step 2: Transform the 2D local vector back to the global coordinate system
u_2d_global = T_inv @ np.append(u_2d_local, 0)  # Append 0 for the normal component (since u_2d_local is 2D)

# make a list with 3D projection vectors sorted from most optimal projection vector to least optimal

shortest_projection_angle_rad_list = np.deg2rad(angles_ranges_sorted)

u_2d_local_list = []
for angle in shortest_projection_angle_rad_list:
    u_2d_local_list.append(np.array([np.cos(angle[0]), np.sin(angle[0])]))
#print(u_2d_local_list)

u_2d_global_list = []
for u_2d_local in u_2d_local_list:
    u_2d_global_list.append(T_inv @ np.append(u_2d_local, 0))
#print(u_2d_global_list)

# Compute the list with global projection directions
projection_direction_list = []
for u_2d_global in u_2d_global_list:
    projection_direction_list.append(np.cross(normal_vector, u_2d_global))
    projection_direction_list[-1] /= np.linalg.norm(projection_direction_list[-1])  # Normalize

#print(projection_direction_list)


Unique values in the corrected mask matrix:  [0. 1. 2.]
Unique values in the aneurysm matrix:  [0. 2.]
Unique values in the surface boundary green matrix:  [0. 1.]
Unique values in dilated_mask: [False  True]
[[140  94 107]
 [140  94 108]
 [140  95 108]
 ...
 [152  91 119]
 [152  92 119]
 [152  93 119]]
Normal vector Ina:  [ 0.65166059  0.6772698  -0.34153198]
Origin Ina:  [146.46527778  92.4212963  112.7662037 ]
[[ 0.         -0.45026653 -0.8928942 ]
 [-0.7585107   0.58186396 -0.29342095]
 [ 0.65166059  0.6772698  -0.34153198]]

[[ 4.43777242  7.51449811 -1.1746154 ]
 [ 3.54487822  7.22107716 -1.51614738]
 [ 3.09461169  7.80294112 -0.83887758]
 ...
 [-4.92615842 -6.85427353  0.51511849]
 [-5.37642495 -6.27240957  1.19238829]
 [-5.82669147 -5.69054562  1.8696581 ]]
[379 322 324 281 241 209 170 132 103 102 101  67  66  37  13  12  11  10
   9   7   6   5   4   2   0  21  18  16  15  40  14  68 104 133 171 211
 247 242 287 282 337 404 329 394 386 425 387 423 381 382 385 391 392 393
 402 

In [4]:
# Set a condition on biggest tolerable variance from smallest neck width
# Example: 7% bigger neck width than the smallest neck width
# The condition will depend on whether we want to prioritise smallest neck width or smallest overlap

def count_valid_pairs(pairs, neck_width_tolerance=0.07):
    """
    Counts the number of (angle, length) pairs where the length is within
    neck_width_tolerance of the smallest length in the sorted list.

    :param pairs: List of (angle, length) tuples sorted by length.
    :param neck_width_tolerance: Tolerance factor (default is 0.07 or 7%).
    :return: Number of pairs satisfying the condition.
    """
    if not pairs:
        return 0

    min_length = pairs[0][1]  # The first entry has the smallest length
    threshold = min_length * (1 + neck_width_tolerance)

    count = sum(1 for _, length in pairs if length <= threshold)
    return count

how_many_planes = count_valid_pairs(angles_ranges_sorted)
print(how_many_planes)

96


In [5]:
# Downsampling function
def downsample_coordinates(x, y, z, factor=2):
    indices = np.arange(0, len(x), factor)
    return x[indices], y[indices], z[indices]

# Find vessel and aneurysm coordinates
x1, y1, z1 = downsample_coordinates(*np.where(seg_data == 1), factor=2)
x2, y2, z2 = downsample_coordinates(*np.where(seg_data == 2), factor=2)

print(normal_vector)
center_x,center_y,center_z = origin[0], origin[1], origin[2]
print(center_x,center_y,center_z)

# Compute two perpendicular vectors
v1, v2 = basis_vector_1, basis_vector_2
print(v1,v2)

# Find valid plane length
def find_plane_endpoints(center, direction, image_shape):
    return min(min(abs((0 - center[i]) / direction[i]), abs((image_shape[i] - center[i]) / direction[i])) if direction[i] != 0 else float('inf') for i in range(3))

# Compute maximum width
def calculate_max_width(x, y, z):
    points = np.vstack((x, y, z)).T  # Combine x, y, z coordinates into a single array of points
    distances = cdist(points, points)  # Calculate pairwise distances between all points
    np.fill_diagonal(distances, 0)  # Set the diagonal to zero because we don't want to compare a point to itself
    max_dist = np.max(distances)  # Find the maximum distance
    return max_dist

image_shape = seg_data.shape  # Image dimensions

# Generate points on the plane
def generate_plane_points(left_start, left_end, right_start, right_end, num_points=100):
    # Create a grid of points on the plane using the two directions
    vector1 = left_end - left_start
    vector2 = right_start - left_start
    points = []
    for i in np.linspace(0, 1, num_points):
        for j in np.linspace(0, 1, num_points):
            point = left_start + i * vector1 + j * vector2
            points.append(point)
    return np.array(points)


# Count red pixels (vessel or aneurysm points)
def count_red_pixels_on_plane(points, seg_data):
    count = 0
    for point in points:
        # Round the point to nearest voxel indices (ensure they are within bounds)
        x, y, z = np.round(point).astype(int)
        if 0 <= x < seg_data.shape[0] and 0 <= y < seg_data.shape[1] and 0 <= z < seg_data.shape[2]:
            if seg_data[x, y, z] == 1:  # Assuming '1' corresponds to the red pixels (vessel)
                count += 1
    return count


[ 0.65166059  0.6772698  -0.34153198]
146.46527777777777 92.42129629629629 112.76620370370371
[ 0.         -0.45026653 -0.8928942 ] [-0.7585107   0.58186396 -0.29342095]


In [6]:
#make dictionary with angle and red pixel count
dict_angle = {}

for i, (angle, max_width) in enumerate(angles_ranges_sorted[0:how_many_planes]):

    print(angle, max_width)
    angle = angle

    angle_rad = np.deg2rad(angle)
    rotated_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
    # direction_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
    max_length = find_plane_endpoints([center_x, center_y, center_z], rotated_vector, image_shape)
    half_width = max_width / 2

    start = np.array([center_x, center_y, center_z])
    # left_start = start - half_width * v1 - half_width * v2
    # right_start = start + half_width * v1 + half_width * v2
    # left_end = left_start + direction_vector * max_length
    # right_end = right_start + direction_vector * max_length

    left_start = start + np.cos(angle_rad) * v1 * -half_width + np.sin(angle_rad) * v2 * -half_width
    right_start = start + np.cos(angle_rad) * v1 * half_width + np.sin(angle_rad) * v2 * half_width

    # Compute the direction vectors from 'start' to each point
    left_vector = left_start - start
    right_vector = right_start - start

    # Normalize the vectors to ensure correct scaling
    left_vector /= np.linalg.norm(left_vector)
    right_vector /= np.linalg.norm(right_vector)

    # Adjust left and right start to be exactly max_width apart
    left_start = start + left_vector * (-max_width / 2)
    right_start = start + right_vector * (max_width / 2)

    # Compute the perpendicular direction (cross product with normal_vector)
    perpendicular_direction = np.cross(normal_vector, left_vector)
    perpendicular_direction /= np.linalg.norm(perpendicular_direction)  # Normalize

    # Move the start points along the perpendicular direction
    left_start += perpendicular_direction * half_width
    right_start -= perpendicular_direction * half_width

    left_end = left_start + rotated_vector * max_length
    right_end = right_start + rotated_vector * max_length

    # Count red pixels on the plane
    red_pixel_count = count_red_pixels_on_plane(generate_plane_points(left_start, left_end, right_start, right_end, num_points=100), seg_data)
    print(f"Red pixel count on plane {angle  :.1f}° : {red_pixel_count}")
    #add red pixel count to dictionary
    dict_angle[angle] = red_pixel_count


92.0 16.553540504743367
Red pixel count on plane 92.0° : 301
272.0 16.55354050474337
Red pixel count on plane 272.0° : 254
93.0 16.57291642878351
Red pixel count on plane 93.0° : 326
273.0 16.57291642878351
Red pixel count on plane 273.0° : 308
94.0 16.587244081933996
Red pixel count on plane 94.0° : 349
274.0 16.587244081934003
Red pixel count on plane 274.0° : 352
98.0 16.594007789719605
Red pixel count on plane 98.0° : 413
278.0 16.594007789719605
Red pixel count on plane 278.0° : 579
91.0 16.595741736175288
Red pixel count on plane 91.0° : 273
271.0 16.59574173617529
Red pixel count on plane 271.0° : 217
95.0 16.596519099852888
Red pixel count on plane 95.0° : 362
275.0 16.596519099852888
Red pixel count on plane 275.0° : 409
97.0 16.599901468896878
Red pixel count on plane 97.0° : 413
277.0 16.599901468896878
Red pixel count on plane 277.0° : 513
96.0 16.600738657279866
Red pixel count on plane 96.0° : 389
276.0 16.60073865727987
Red pixel count on plane 276.0° : 459
99.0 16.62768

In [7]:
print(dict_angle)
# sorted_dict = sorted(dict_angle.items(), key=lambda x: x[1])
# print(sorted_dict)

{np.float64(92.0): 301, np.float64(272.0): 254, np.float64(93.0): 326, np.float64(273.0): 308, np.float64(94.0): 349, np.float64(274.0): 352, np.float64(98.0): 413, np.float64(278.0): 579, np.float64(91.0): 273, np.float64(271.0): 217, np.float64(95.0): 362, np.float64(275.0): 409, np.float64(97.0): 413, np.float64(277.0): 513, np.float64(96.0): 389, np.float64(276.0): 459, np.float64(99.0): 418, np.float64(279.0): 621, np.float64(100.0): 437, np.float64(280.0): 670, np.float64(90.0): 258, np.float64(270.0): 184, np.float64(101.0): 438, np.float64(281.0): 724, np.float64(282.0): 778, np.float64(102.0): 461, np.float64(89.0): 218, np.float64(269.0): 149, np.float64(103.0): 496, np.float64(283.0): 844, np.float64(104.0): 520, np.float64(284.0): 920, np.float64(268.0): 124, np.float64(88.0): 177, np.float64(105.0): 516, np.float64(285.0): 1000, np.float64(106.0): 511, np.float64(286.0): 1072, np.float64(107.0): 515, np.float64(287.0): 1137, np.float64(108.0): 505, np.float64(288.0): 1210,

In [8]:
dict_both_sides = {}
processed = set()

for angle, red_pixels in dict_angle.items():
    if angle in processed:
        continue  # Skip angles already processed

    opposite_angle = angle + 180 if (angle + 180) in dict_angle else angle - 180

    if opposite_angle in dict_angle:
        total_red_pixels = red_pixels + dict_angle[opposite_angle]
        
        # Ensure the smaller angle is always the key
        chosen_angle = min(angle, opposite_angle)
        paired_angle = max(angle, opposite_angle)

        dict_both_sides[chosen_angle] = {paired_angle: total_red_pixels}
        processed.add(angle)
        processed.add(opposite_angle)

print(dict_both_sides)

# Sort dictionary based on the summed red pixel values
sorted_dict_both_sides = dict(sorted(dict_both_sides.items(), key=lambda item: list(item[1].values())[0]))

print(sorted_dict_both_sides)

{np.float64(92.0): {np.float64(272.0): 555}, np.float64(93.0): {np.float64(273.0): 634}, np.float64(94.0): {np.float64(274.0): 701}, np.float64(98.0): {np.float64(278.0): 992}, np.float64(91.0): {np.float64(271.0): 490}, np.float64(95.0): {np.float64(275.0): 771}, np.float64(97.0): {np.float64(277.0): 926}, np.float64(96.0): {np.float64(276.0): 848}, np.float64(99.0): {np.float64(279.0): 1039}, np.float64(100.0): {np.float64(280.0): 1107}, np.float64(90.0): {np.float64(270.0): 442}, np.float64(101.0): {np.float64(281.0): 1162}, np.float64(102.0): {np.float64(282.0): 1239}, np.float64(89.0): {np.float64(269.0): 367}, np.float64(103.0): {np.float64(283.0): 1340}, np.float64(104.0): {np.float64(284.0): 1440}, np.float64(88.0): {np.float64(268.0): 301}, np.float64(105.0): {np.float64(285.0): 1516}, np.float64(106.0): {np.float64(286.0): 1583}, np.float64(107.0): {np.float64(287.0): 1652}, np.float64(108.0): {np.float64(288.0): 1715}, np.float64(87.0): {np.float64(267.0): 243}, np.float64(1

In [ ]:
# Calculate the unit vector in the 2D plane corresponding to the projection angle
print(next(iter(sorted_dict_both_sides)))
optimal_projection_angle_rad = np.deg2rad(next(iter(sorted_dict_both_sides)))  # Convert theta to radians
optimal_u_2d_local = np.array([np.cos(optimal_projection_angle_rad), np.sin(optimal_projection_angle_rad)])

# Transform the 2D local vector back to the global coordinate system
optimal_u_2d_global = T_inv @ np.append(optimal_u_2d_local, 0)  # Append 0 for the normal component (since u_2d_local is 2D)

# Find the final optimal projection direction in the global coordinate system
optimal_projection_direction = np.cross(normal_vector, u_2d_global)
optimal_projection_direction /= np.linalg.norm(optimal_projection_direction)  # Normalize
print(optimal_projection_direction)

# Convert to DSA angles
w_x, w_y, w_z = optimal_projection_direction # get the x,y,z components

if w_y >= 0:    #fluoroscopic rotation angle rho
    rho = -np.arcsin(w_x)
else:
    rho = np.arcsin(w_x)

denominator = np.sqrt(1 - w_x**2)
if w_y >= 0:  #fluoroscopic angulation angle psi
    psi = np.arcsin(w_z / denominator)
else:
    psi = -np.arcsin(w_z / denominator)

# Convert to degrees for easier interpretation
rho_deg = np.degrees(rho)
psi_deg = np.degrees(psi)

print(f"Final optimal DSA Rotation Angle (ρ): {rho_deg:.2f}°")
print(f"Final optimal DSA Angulation Angle (ψ): {psi_deg:.2f}°")

74.0
[ 0.74917217 -0.64513745  0.15012902]
Final optimal DSA Rotation Angle (ρ): 48.52°
Final optimal DSA Angulation Angle (ψ): -13.10°


#### Visualize the result

In [10]:
# Dash app
app = dash.Dash(__name__)
app.layout = html.Div([
    html.H3("3D Visualization of Cerebral Vessels, Aneurysms, and Viewing Planes"),
    dcc.Graph(id='3d-plot', config={'scrollZoom': True}, style={'height': '80vh'}),
    html.Label("Number of Planes:"),
    dcc.Slider(id='num-planes-slider', min=1, max=360, step=1, value=how_many_planes,
               marks={i: str(i) for i in range(4, 37, 4)}, tooltip={"placement": "bottom", "always_visible": True})
])

# Generate a list of distinct colors from Plotly's predefined color scale
color_list = pc.qualitative.Set1  # or you can choose other color scales like Set2, Set3, etc.

@app.callback(Output('3d-plot', 'figure'), Input('num-planes-slider', 'value'))
def update_3d_plot(_):
    fig = go.Figure()

    # Add vessels, aneurysms, and connection region
    fig.add_trace(go.Scatter3d(x=x1, y=y1, z=z1, mode='markers', marker=dict(size=2, color='red'), name="Vessels"))
    fig.add_trace(go.Scatter3d(x=x2, y=y2, z=z2, mode='markers', marker=dict(size=2, color='blue'), name="Aneurysms"))
    fig.add_trace(go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=2, color='green'), name="Connection"))

    # Generate a list of distinct colors from Plotly's predefined color scale
    color_list = pc.qualitative.Set1  # Choose color set

    for i, (angle, max_width) in enumerate(angles_ranges_sorted[0:1]):
        plane_color = color_list[i % len(color_list)]  # Ensure we loop through the color list

        angle = angle

        angle_rad = np.deg2rad(angle)
        rotated_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
        # direction_vector = np.cos(angle_rad) * v1 + np.sin(angle_rad) * v2
        max_length = find_plane_endpoints([center_x, center_y, center_z], rotated_vector, image_shape)
        half_width = max_width / 2

        start = np.array([center_x, center_y, center_z])
        # left_start = start - half_width * v1 - half_width * v2
        # right_start = start + half_width * v1 + half_width * v2
        # left_end = left_start + direction_vector * max_length
        # right_end = right_start + direction_vector * max_length

        left_start = start + np.cos(angle_rad) * v1 * -half_width + np.sin(angle_rad) * v2 * -half_width
        right_start = start + np.cos(angle_rad) * v1 * half_width + np.sin(angle_rad) * v2 * half_width

        # Compute the direction vectors from 'start' to each point
        left_vector = left_start - start
        right_vector = right_start - start

        # Normalize the vectors to ensure correct scaling
        left_vector /= np.linalg.norm(left_vector)
        right_vector /= np.linalg.norm(right_vector)

        # Adjust left and right start to be exactly max_width apart
        left_start = start + left_vector * (-max_width / 2)
        right_start = start + right_vector * (max_width / 2)

        # Compute the perpendicular direction (cross product with normal_vector)
        perpendicular_direction = np.cross(normal_vector, left_vector)
        perpendicular_direction /= np.linalg.norm(perpendicular_direction)  # Normalize

        # Move the start points along the perpendicular direction
        left_start += perpendicular_direction * half_width
        right_start -= perpendicular_direction * half_width

        left_end = left_start + rotated_vector * max_length
        right_end = right_start + rotated_vector * max_length

        fig.add_trace(go.Mesh3d(
            x=[left_start[0], left_end[0], right_end[0], right_start[0]],
            y=[left_start[1], left_end[1], right_end[1], right_start[1]],
            z=[left_start[2], left_end[2], right_end[2], right_start[2]],
            i=[0, 1, 2, 0], j=[1, 2, 3, 2], k=[2, 3, 0, 3],
            opacity=0.5, color=plane_color, name=f"Plane {angle:.1f}°"
        ))

        # Count red pixels on the plane
        red_pixel_count = count_red_pixels_on_plane(generate_plane_points(left_start, left_end, right_start, right_end, num_points=100), seg_data)
        print(f"Color: {plane_color}, Angle: {angle:.1f}°, Width: {max_width}, Red pixel count on plane: {red_pixel_count}")

    fig.update_layout(scene=dict(xaxis_title="X", yaxis_title="Y", zaxis_title="Z"), margin=dict(l=0, r=0, b=0, t=0))
    return fig

if __name__ == '__main__':
    app.run_server(debug=True , port=8052)
    #app.run_server(debug=True)



ObsoleteAttributeException: app.run_server has been replaced by app.run